# Generated by Django 4.2.30 on 2026-09-07 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_session_counter_number_session_red_flag_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='assisted_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LinkedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(default='health_record', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_records', to='core.session')),
            ],
        ),
    ]
