# Generated by Django 4.2.30 on 2026-09-07 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patient_age_patient_sex_session_assisted_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='doctor_instructions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(choices=[('PATIENT', 'Patient'), ('AI', 'AI Assistant'), ('STAFF', 'Staff'), ('DOCTOR', 'Doctor'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.session')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
